name: 构建和推送 Docker 镜像到 GHCR

on:
  workflow_dispatch: # 只允许手动触发

jobs:
  build-and-push:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/amd64,linux/arm64 # 指定需要构建的平台

      - name: Get Latest GitHub Release
        id: get_latest_release
        run: |
          RELEASE_TAG=$(gh release list --limit 1 --json tagName | jq -r '.[0].tagName')
          if [[ -z "$RELEASE_TAG" ]]; then
            echo "No release found, using default tag v1.0.0"
            RELEASE_TAG="v1.0.0"
          fi
          echo "RELEASE_TAG=$RELEASE_TAG" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build 和 Push Docker Image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ steps.get_latest_release.outputs.RELEASE_TAG }}
            ghcr.io/${{ github.repository }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max